### ISSUE TITLE
Can we pull some of these improvements into the community supported Kibana 3 repo?

### ISSUE THREAD

**Issue by Asimov4** [chenryn/kibana-authorization#19]
Hi!

I saw your post on https://discuss.elastic.co/t/who-out-there-is-still-using-kibana-3/24230/41 and love what you did!
Can we pull some of these improvements into the community supported Kibana 3 repo?
https://github.com/kibana-community/kibana3

I'm thinking we would take the Angular and elasticjs upgrade as well as all the panel improvements but would leave the authorization and authentication layers behind to let any pick their auth stack.

**Comment by chenryn** [comment]
well, just `rm -rf ./kbnauth` to solve this problem.I'm upgrading some other panels to use aggregation apis. Should I pull to community repo now or later?

**Comment by Asimov4** [comment]
Neat! Let's wait for your upgrades then. Are you upgrading Kibana for Elasticsearch 2.0?

**Comment by crashish** [comment]
I know that converting everything to aggregations is on your TODO list, but is there any update on this? I'm looking to upgrade my 1.7 cluster to 2.x and would love to continue using K3 with your changes. I found https://github.com/gigya/kibana/tree/3.0 that supports ES2 but it doesn't have your additions.

**Comment by chenryn** [comment]
@crashish @Asimov4 my friends already convert completely at his branch, see: https://github.com/childe/kibana-authorization/tree/dev

**Comment by crashish** [comment]
Awesome, thanks for the link!

**Comment by mzamora717** [comment]
Hi @chenryn I just noticed that the "table" panel type does not support aggregations and the "must not" filter does not work. If you click on the "exclude" icon to exclude certain queries, the table query does not support it.

**Comment by chenryn** [comment]
@mzamora717 We didn't change the filterSrv.js in kibana source code. Can you repetition the mustNot error in official kibana3?

**Comment by mzamora717** [comment]
@chenryn did you make updates to the terms panel? I noticed it does not work b/c it is still using facets.
curl -XGET 'http://sqvlhglr002.test.cm.com:9200/_all/_search?pretty' -d '{
  "facets": {
    "terms": {
      "terms": {
        "field": "lvl",
        "size": 10,
        "order": "count",
        "exclude": []
      },
      "facet_filter": {
        "fquery": {
          "query": {
            "filtered": {
              "query": {
                "bool": {
                  "should": [
                    {
                      "query_string": {
                        "query": "*"
                      }
                    }
                  ]
                }
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "match_all": {}
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}' 

I get this error:
Caused by: SearchParseException[failed to parse search source [{"facets":{"terms":{"terms":{"field":"lvl","size":10,"order":"count","exclude":[]},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"*"}}]}},"filter":{"bool":{"must":[{"match_all":{}}]}}}}}}}},"size":0}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:854)
        ... 12 more

**Comment by chenryn** [comment]
@mzamora717 this repo only support to es1.x. you may need to try https://github.com/childe/kibana-authorization/tree/dev
